### ISSUE TITLE
How to understand your code

### ISSUE THREAD

**Issue by tangeroo** [GitGaoXing/Unity3MXB#2]
Hi,
  Very exciting to see your project. I'm new in this field. And I do not have any basic knowledge about unity. So I would appreciate any suggestions for what I need to know if I want to understand your code.
Thank you.

**Comment by GitGaoXing** [comment]
https://docs.bentley.com/LiveContent/web/ContextCapture%20Help-v9/en/GUID-CED0ABE6-2EE3-458D-9810-D87EC3C521BD.html

**Comment by GitGaoXing** [comment]
first. figure out what 3mx is.
