### ISSUE TITLE
Not 3mx in scene

### ISSUE THREAD

**Issue by rjgarnicap** [GitGaoXing/Unity3MXB#5]
Hi, thank you for your code. I'm new in Unity and I have several contextcapture models but I don't understand how to load a model in Unity using your code. I did an attemp but it was not successfull. Again, thanks for your project.

**Comment by GitGaoXing** [comment]
![image](https://user-images.githubusercontent.com/16396037/109460761-18883a80-7a9c-11eb-8429-7cbe009404a4.png)

**Comment by GitGaoXing** [comment]
put the url of your 3mx model here

**Comment by GitGaoXing** [comment]
Hierarchy->SampleModels->3mx->Url

**Comment by rjgarnicap** [comment]
Thank you. I've tried again but my 3mx model doesn't appear. I've attached an image.
![T3mx](https://user-images.githubusercontent.com/79600171/109556509-87fe2a00-7a9c-11eb-8d2d-1d1d4ec2443b.png)

I have Unity 2018.4, maybe that's the problem.

Thank you

**Comment by GitGaoXing** [comment]
Unity 2018.4 works fine for me. You need to run the Editor to load the 3mx. it is runtime loading.

**Comment by rjgarnicap** [comment]
Thank you. I've could load the model in the scene.
