### ISSUE TITLE
Problem trying to see 3mx file using VR camera

### ISSUE THREAD

**Issue by rjgarnicap** [GitGaoXing/Unity3MXB#6]
Dear GaoXing, 

First, congratulations for your tool to visualize 3mx files in Unity. Nice job.

I have a question. I've could run the tool and see my files. But now I want to change de camera for a VR Player to see model with other perspective. When I delete camera and I use VR player then model doesn't appear. I'm guessing that model only appears when you use the camera of the scene, is that correct?

I supposed that I have create a script to change the camera.

Thank you, and sorry for the inconvenience.

**Comment by GitGaoXing** [comment]
yes, u need to change the code
